### PR TITLE
change id-type to float

### LINKED ISSUE #18: Error processing Vivarium E. Coli File
## Description

The vivarium_ecoli.simularium file fails to process:

```
2021-07-09 23:22:51.783 (104012.836s) [File IO         ]   simulation_cache.cpp:187   INFO|Simularium file trajectory/vivarium_ecoli.simularium found on AWS S3
...
2021-07-09 23:22:52.345 (104013.398s) [File IO         ]   simularium_binary_file.:14    INFO|Creating new simularium binary file at
2021-07-09 23:22:52.345 (104013.398s) [File IO         ]   simulation_cache.cpp:216   INFO|1022 frames found in simularium json file
terminate called after throwing an instance of 'Json::LogicError'
  what():  double out of Int range
```

## Expected Behavior

This file should stream similarly to the other request-able files

Request vivarium_ecoli.simularium from the simularium-engine application

## Environment

Deployed

### PR DESCRIPTION
**Pull request by ghost**
**Pull request recommendations:**

- [ ] Name your pull request _your-development-type/short-description_. Ex: _feature/read-tiff-files_
- [x] Link to any relevant issue in the PR description. Ex: _Resolves [gh-##], adds tiff file format support_
- [x] Provide description and context of changes.
- [ ] Provide relevant tests for your feature or bug fix.
- [ ] Provide or update documentation for any feature added by your pull request.

Thanks for contributing!

Fixes https://github.com/allen-cell-animated/simularium-engine/issues/18

Agent IDs greater than the integer limit (~2e9) cause this crash; the fix is to interpret the IDs as floats (limit ~1e38). IIRC, the offending ID was ~1e17.

### CODE REVIEW

**Comment by schoinh** [comment]
Part of me does wonder if @blairlyons 's upcoming change to simulariumio should be sufficient, unless we expect there to be more than ~2e9 agent IDs in a trajectory realistically. (I think I have mild PTSD with floats, even if we're not doing / planning on doing any math with these IDs.... currently.) But approving per today's dev meeting.

**Review by schoinh — APPROVED** [review]

**Comment by toloudis** [comment]
could we just go to 64-bit ints?  I'm not super thrilled about representing very large integers with floating point especially if they have to go through json

**Comment by EricJIsaac** [comment]
> could we just go to 64-bit ints? I'm not super thrilled about representing very large integers with floating point especially if they have to go through json
> 
> Also, is an agent id that large really legit? Can we impose some limit in simulariumio and elsewhere?

Not opposed to doing an int64, can swap that out. JsonCPP uses a double for this value (which is how it even parsed at all), so I do not know if this will actually guarantee integer like behavior in parsing/processing.

@blairlyons confirmed that the vivarium-ecoli file should be able to stay w/in the int limit; generally, imposing an INT_MAX system-wide is also a workable fix for #18

**Comment by toloudis** [comment]
@blairlyons What do you think we should do here?  Can we guarantee (and impose as a limit) that agent id's must fit into a 32-bit integer?  Or do we need to expand it to 64 bits. 

I'd like to close this - based on the comments it seems like we don't need to use the floating point change made here and if 32 bits is really ok then we don't need to modify anything on the engine side?

**Comment by blairlyons** [comment]
yeah 32-bit is fine, I'll fix the data and check for it in simulariumio https://github.com/simularium/simulariumio/issues/78

**Comment by blairlyons** [comment]
this issue is fixed by [validating data](https://github.com/simularium/simulariumio/issues/78) and this engine is depreciated, so we won't merge this

**Pull request closed without merging**
